/* 产品数据集中维护，后续新增产品时只需在此追加对象。 */
window.PRODUCT_CATEGORIES = [
  { id: "all", label: "全部臻品", short: "全部" },
  { id: "bracelet", label: "手串系列", short: "手串" },
  { id: "pendant", label: "吊坠系列", short: "吊坠" },
  { id: "bangle", label: "手镯系列", short: "手镯" },
  { id: "accessory", label: "配饰系列", short: "配饰" },
  { id: "decor", label: "摆件系列", short: "摆件" },
  { id: "creative", label: "文创系列", short: "文创" },
  { id: "wellness", label: "康养关怀类", short: "康养" },
  { id: "heritage", label: "非遗工艺类", short: "非遗" },
  { id: "trace", label: "溯源臻选类", short: "溯源" }
];

window.PRODUCTS = [
  {
    id: "red-crystal-bracelet",
    category: "bracelet",
    name: "天然红晶砂手串",
    number: "DLYS-SC-001",
    material: "天然红晶砂、弹力绳",
    size: "珠径多规格可选，手围可调",
    tagline: "色泽温润，颗颗红透",
    description: "精选贵州万山天然红晶砂，经制珠、抛光与手工串制，呈现通透温润的东方红韵。适合日常佩戴，也适合作为节庆与礼赠之选。",
    meaning: "圆珠相连，寓意圆融顺遂；朱砂红承载喜庆、吉祥与守护的传统文化意象。",
    images: ["images/products/bracelet-red-1.png", "images/products/bracelet-red-2.png", "images/products/bracelet-red-3.png"],
    featured: true,
    featuredOrder: 4
  },
  {
    id: "crystal-sand-bracelet",
    category: "bracelet",
    name: "天然晶体砂手串",
    number: "DLYS-SC-002",
    material: "天然晶体砂、弹力绳",
    size: "珠径多规格可选，手围可调",
    tagline: "晶体肌理，光下见真章",
    description: "保留天然晶体砂独特的矿物肌理，以细致打磨展现晶体光泽。每一串在纹理与色泽上都略有差异，形成独一无二的自然印记。",
    meaning: "取晶石坚韧与圆珠和合之意，寄托坚定、圆满的美好愿望。",
    images: ["images/products/bracelet-crystal-1.png", "images/products/bracelet-crystal-2.png", "images/products/bracelet-crystal-3.png"]
  },
  {
    id: "diy-red-bracelet",
    category: "bracelet",
    name: "6mm 红晶砂 DIY 手串",
    number: "DLYS-SC-003",
    material: "天然红晶砂、设计配珠",
    size: "珠径约 6mm，款式可选",
    tagline: "轻巧叠戴，自在搭配",
    description: "以轻巧的 6mm 红晶砂珠为主，可根据日常穿搭选择不同配珠与编排方式，让传统朱砂进入更年轻的生活场景。",
    meaning: "小珠成串，象征点滴积福、日日安然。",
    images: ["images/products/bracelet-diy-1.png", "images/products/bracelet-diy-2.png", "images/products/bracelet-diy-3.png"]
  },
  {
    id: "red-pingan-pendant",
    category: "pendant",
    name: "红晶砂平安扣吊坠",
    number: "DLYS-DZ-001",
    material: "天然红晶砂、手工编绳",
    size: "成人款、儿童款及多种绳款可选",
    tagline: "圆满无缺，岁岁享平安",
    description: "经典平安扣形制与天然红晶砂相结合，保留圆润饱满的轮廓与细腻砂感。多种编绳风格可适配不同年龄与佩戴场景。",
    meaning: "平安扣外圆内圆，取圆满通达、平安顺遂之意，是东方饰品中经久不衰的吉祥形制。",
    images: ["images/products/pendant-pingan-1.png", "images/products/pendant-pingan-2.png", "images/products/pendant-pingan-3.png"],
    featured: true,
    featuredOrder: 5
  },
  {
    id: "shangui-pendant",
    category: "pendant",
    name: "山鬼花钱平安扣",
    number: "DLYS-DZ-002",
    material: "天然红晶砂、手工编绳",
    size: "多款式可选，尺寸以实物为准",
    tagline: "古意纹样，方寸纳吉",
    description: "以传统山鬼花钱纹样为灵感，在圆形朱砂饰面上呈现古朴文字与纹饰，兼具传统审美和日常佩戴质感。",
    meaning: "山鬼花钱纹样承载民间纳吉护佑的文化寄托，圆形轮廓寓意周全圆满。",
    images: ["images/products/pendant-shangui-1.png", "images/products/pendant-shangui-2.png", "images/products/pendant-shangui-3.png"],
    featured: true
  },
  {
    id: "raw-stone-pendant",
    category: "pendant",
    name: "天然朱砂原石吊坠",
    number: "DLYS-DZ-003",
    material: "天然朱砂原石、编绳配件",
    size: "孤品随形，具体以实物为准",
    tagline: "随形而琢，一石一貌",
    description: "依据原石天然形态进行随形设计与精细打磨，尽可能保留矿物结晶与原生纹理。不同原石在色泽、肌理与轮廓上各不相同。",
    meaning: "尊重自然本真，寓意守正、坚韧与独一无二。",
    images: ["images/products/pendant-raw-1.png", "images/products/pendant-raw-2.png", "images/products/pendant-raw-3.png"]
  },
  {
    id: "lacquer-bead-pendant",
    category: "pendant",
    name: "珐琅彩大漆珠吊坠",
    number: "DLYS-DZ-004",
    material: "朱砂、大漆、珐琅彩工艺配件",
    size: "多款式可选，手工制品略有差异",
    tagline: "非遗技艺，色彩相生",
    description: "将朱砂红与大漆、珐琅彩等东方工艺语言融合，在小巧珠体上呈现丰富层次，适合新中式穿搭与精致礼赠。",
    meaning: "漆色历久弥新，朱红喜庆温厚，寓意美好长存、福泽绵延。",
    images: ["images/products/pendant-lacquer-1.png", "images/products/pendant-lacquer-2.png", "images/products/pendant-lacquer-3.png"]
  },
  {
    id: "wushipai-pendant",
    category: "pendant",
    name: "红晶砂无事牌吊坠",
    number: "DLYS-DZ-005",
    material: "天然红晶砂、手工编绳",
    size: "多规格可选，尺寸以实物为准",
    tagline: "素面留白，无事常安",
    description: "以素面简形突出朱砂本身的细腻色泽，形制利落、温润含蓄，适合偏爱简约东方美学的佩戴者。",
    meaning: "无饰亦无事，寄托平安无虞、自在从容的生活愿景。",
    images: ["images/products/pendant-wushipai-1.png", "images/products/pendant-wushipai-2.png", "images/products/pendant-wushipai-3.png"]
  },
  {
    id: "three-flower-bangle",
    category: "bangle",
    name: "珐琅彩乾坤三花手镯",
    number: "DLYS-SZ-001",
    material: "朱砂、珐琅彩工艺配件",
    size: "圈口多规格可选",
    tagline: "三花映彩，乾坤有序",
    description: "以流畅圆环为主体，点缀珐琅彩花饰，将朱砂红与金色细节相衬，形成明快又庄重的新中式手饰。",
    meaning: "圆环象征圆满，三花寄托花开见喜、和美相伴。",
    images: ["images/products/bangle-threeflower-1.png", "images/products/bangle-threeflower-2.png", "images/products/bangle-threeflower-3.png"],
    featured: true
  },
  {
    id: "guiren-bangle",
    category: "bangle",
    name: "珐琅彩贵人手镯",
    number: "DLYS-SZ-002",
    material: "朱砂、珐琅彩、金色工艺配件",
    size: "圈口及花青、碧清、红金、松石绿可选",
    tagline: "流光溢彩，腕间国风",
    description: "以朱砂红为主调，搭配花青、碧清、红金或松石绿等珐琅色彩，视觉鲜明，适合节庆、礼宴与国风穿搭。",
    meaning: "以“贵人”为名，寄托遇见善缘、相携相助的美好愿望。",
    images: ["images/products/bangle-guiren-1.png", "images/products/bangle-guiren-2.png", "images/products/bangle-guiren-3.png"]
  },
  {
    id: "red-sand-earrings",
    category: "accessory",
    name: "红砂雅韵耳钉",
    number: "DLYS-PS-001",
    material: "红砂饰面、耳饰金属配件",
    size: "多款式可选",
    tagline: "一抹朱红，点亮东方气韵",
    description: "将朱砂红浓缩为耳畔的一点亮色，造型精巧利落，可与日常通勤或新中式服饰自然搭配。",
    meaning: "朱红点睛，寓意见喜、添彩。",
    images: ["images/products/accessory-earrings-1.png", "images/products/accessory-earrings-2.png", "images/products/accessory-earrings-3.png"]
  },
  {
    id: "pixiu-charm",
    category: "accessory",
    name: "朱砂貔貅小挂件",
    number: "DLYS-PS-002",
    material: "朱砂、编绳与配饰件",
    size: "小巧便携，多款式可选",
    tagline: "灵巧随身，古意新用",
    description: "以传统瑞兽貔貅为造型灵感，结合现代挂件结构，可用于随身包袋或手机挂饰，轻巧而有辨识度。",
    meaning: "貔貅是传统瑞兽意象，常被寄托纳福聚财的民俗愿望。",
    images: ["images/products/accessory-pixiu-1.png", "images/products/accessory-pixiu-2.png", "images/products/accessory-pixiu-3.png"]
  },
  {
    id: "lacquer-car-charm",
    category: "accessory",
    name: "朱砂大漆工艺车挂",
    number: "DLYS-PS-003",
    material: "朱砂、大漆、编绳配件",
    size: "多造型可选",
    tagline: "一挂东方红，一路皆从容",
    description: "融合朱砂与大漆质感，通过编结、流苏与主题饰件组成层次丰富的车内挂饰，亦可用于空间软装点缀。",
    meaning: "承载出入平安、一路顺遂的传统祝愿。",
    images: ["images/products/accessory-car-1.png", "images/products/accessory-car-2.png", "images/products/accessory-car-3.png"]
  },
  {
    id: "cinnabar-crystal-sphere",
    category: "decor",
    name: "天然朱砂水晶球",
    number: "DLYS-BJ-001",
    material: "天然朱砂原石、透明晶体球、工艺底座",
    size: "多规格与主题底座可定制",
    tagline: "原矿入景，方寸藏山河",
    description: "将天然朱砂原石封存于透明球体中，保留矿物天然纹理，并搭配主题雕刻底座，适合案头陈设、商务礼赠与个人收藏。",
    meaning: "圆球象征圆融完整；水晶球转动的视觉意象寄托时来运转、财源广进。",
    images: ["images/products/decor-sphere-1.png", "images/products/decor-sphere-2.png", "images/products/decor-sphere-3.png"],
    featured: true
  },
  {
    id: "cinnabar-night-lamp",
    category: "decor",
    name: "朱砂柔光小夜灯",
    number: "DLYS-BJ-002",
    material: "朱砂工艺画面、木质灯框、灯光组件",
    size: "桌面陈设尺寸，多主题可选",
    tagline: "一盏暖灯，照见东方祝福",
    description: "将朱砂书画意象与暖光小夜灯结合，在实用照明中融入“福”“安”等东方主题，适合卧室、茶席与礼赠场景。",
    meaning: "灯火长明，寓意家宅温暖、平安有福。",
    images: ["images/products/decor-lamp-1.png", "images/products/decor-lamp-2.png", "images/products/decor-lamp-3.png"]
  },
  {
    id: "cinnabar-vessel",
    category: "pendant",
    name: "朱砂福韵宝瓶",
    number: "DLYS-DZ-020",
    material: "朱砂工艺材质、主题底座",
    size: "桌面摆件，多规格可选",
    tagline: "宝瓶纳福，案头生辉",
    description: "以传统宝瓶形制为基础，呈现厚重朱红与金色纹样，整体端庄稳重，适合玄关、书房与商务空间陈设。",
    meaning: "宝瓶谐音“保平”，寓意平安纳福、圆满丰盈。",
    images: ["images/products/decor-bottle-1.png", "images/products/decor-bottle-2.png", "images/products/decor-bottle-3.png"]
  },
  {
    id: "wanshan-painting",
    category: "creative",
    name: "万山红遍朱砂画",
    number: "DLYS-WC-001",
    material: "贵州朱砂矿物颜料、装裱画框",
    size: "代表款约 89 × 117cm，支持主题定制",
    tagline: "矿物入画，色凝千年",
    description: "以贵州高品质朱砂为创作材料，融合传统矿物颜料技法与现代构图。浓郁朱红在光影中呈现深浅变化，适合艺术陈设与高端礼赠。",
    meaning: "万山红遍象征山河壮丽、事业兴盛与鸿运绵长。",
    images: ["images/products/painting-wanshan-gallery.webp", "images/products/painting-1.png", "images/products/painting-2.png", "images/products/painting-3.png"],
    featured: true
  },
  {
    id: "cinnabar-fortune-bag",
    category: "accessory",
    name: "朱砂纳福袋",
    number: "DLYS-PS-007",
    material: "朱砂主题饰件、织物与编绳",
    size: "多主题、多规格可选",
    tagline: "小巧纳福，礼意周全",
    description: "以福袋为载体融入朱砂主题饰件与传统编结，体量轻巧，适合作为节庆伴手礼、活动纪念与文旅礼品。",
    meaning: "福袋纳福，寄托福气常在、喜乐随行。",
    images: ["images/products/creative-fubag-1.png", "images/products/creative-fubag-2.png", "images/products/creative-fubag-3.png"]
  },
  {
    id: "incense-dao-beads",
    category: "wellness",
    name: "东方合香道珠",
    number: "DLYS-KY-001",
    material: "天然香材、朱砂主题配珠、手工编绳",
    size: "多种香方与珠径可选，手围可调",
    tagline: "古方合香，腕间清雅",
    description: "以传统合香理念为灵感，将天然香材制成温润珠体，并以朱砂主题配珠点睛。玫瑰、香肌、辟暑、薰衣等不同香韵均采用东方场景呈现，适合作为日常雅佩与文化礼赠。",
    meaning: "合香承载古人用香、品香与修心的生活美学，圆珠相连寓意和合圆满、雅意常伴。",
    images: ["images/products/wellness-incense-1.jpg", "images/products/wellness-incense-2.jpg", "images/products/wellness-incense-3.jpg", "images/products/wellness-incense-4.jpg"],
    featured: true,
    featuredOrder: 1
  },
  {
    id: "cinnabar-wellness-pillow",
    category: "wellness",
    name: "朱砂养心安神枕",
    number: "DLYS-KY-002",
    material: "锦缎枕套、草本填充层、朱砂主题复合草本包",
    size: "礼盒装，具体尺寸以实物为准",
    tagline: "层叠匠作，安享静谧",
    description: "采用锦缎枕套、无纺布内胆、荞麦壳填充与复合草本包的分层结构，兼顾支撑、透气与日常使用体验。产品配有完整礼盒包装，适合家庭关怀与节庆礼赠。",
    meaning: "以枕寄情，承载对家人安然休憩、从容生活的温厚祝愿。",
    images: ["images/products/wellness-pillow-1.jpg", "images/products/wellness-pillow-2.jpg", "images/products/wellness-pillow-3.jpg"],
    featured: true,
    featuredOrder: 2
  },
  {
    id: "cinnabar-incense-holder",
    category: "heritage",
    subcategory: "陶艺类",
    name: "朱砂陶香插",
    number: "DLYS-FY-001",
    material: "陶土、朱砂工艺层、手工描金",
    size: "多款香插造型，手工作品略有差异",
    tagline: "朱砂入陶，一席清香",
    description: "以陶艺塑形承载朱砂呈色，器身保留手作肌理与描金细节，可置于茶席、书房与香事空间。选用资料中带有完整品名说明的规范场景图展示。",
    meaning: "香席清雅，朱红温厚，寄托静心自持、和美安然的东方生活意趣。",
    images: ["images/products/heritage-incense-holder-1.webp", "images/products/heritage-incense-holder-2.webp", "images/products/heritage-incense-holder-3.webp"],
    featured: true,
    featuredOrder: 3
  },
  {
    id: "ma-cinnabar-seal-paste",
    category: "trace",
    name: "MA 古法朱砂印泥",
    number: "DLYS-MA-001",
    material: "原矿朱砂、植物油、天然纤维等传统印泥材料",
    size: "多规格印泥盒可选",
    tagline: "原矿入印，钤藏朱红",
    description: "MA 溯源中心原矿朱砂印泥系列，以原矿朱砂为核心材料，延续传统印泥调制与养护思路，色泽庄重饱满，适用于书画钤印与文化收藏场景。",
    meaning: "一方朱印连接书画、金石与信物传统，寓意郑重、守信与文脉相承。",
    images: ["images/products/trace-ink-1.jpg", "images/products/trace-ink-2.jpg", "images/products/trace-ink-3.jpg"]
  },
  {
    id: "ma-raw-stone-decor",
    category: "trace",
    name: "MA 朱砂原石摆件",
    number: "DLYS-MA-004",
    material: "天然朱砂原石、主题底座",
    size: "天然孤品，规格依原石而定",
    tagline: "山石天成，原矿入景",
    description: "甄选具有鲜明朱砂结晶与天然形态的原石，经清理、稳固和底座适配后形成观赏摆件，完整保留矿物的原生色泽、层理与体量感。",
    meaning: "原石如山，象征根基稳固、守正笃实，也呈现贵州万山独特的矿物文化记忆。",
    images: [
      "images/products/trace-raw-decor-4.webp",
      "images/products/trace-raw-decor-5.webp",
      "images/products/trace-raw-decor-6.webp",
      "images/products/trace-raw-decor-7.webp",
      "images/products/trace-raw-decor-8.webp",
      "images/products/trace-raw-decor-1.jpg",
      "images/products/trace-raw-decor-2.jpg",
      "images/products/trace-raw-decor-3.jpg"
    ]
  }
];

/* 根据完整产品资料补充的饰品与文创系列。 */
window.PRODUCTS.push(
  {
    id: "enamel-chibao-bracelet",
    category: "bracelet",
    name: "珐琅彩赤宝手串",
    number: "DLYS-SC-004",
    material: "朱砂、珐琅彩工艺配件、弹力绳",
    size: "多珠径与配色可选，手围可调",
    tagline: "珐琅点彩，国潮入腕",
    description: "以朱砂圆珠为主，融入珐琅彩花饰与金色细节，呈现鲜明而不失庄重的新中式风格。",
    meaning: "圆珠相连寓意圆融顺遂，花彩图案寄托花开见喜、华彩常伴。",
    images: ["images/products/bracelet-enamel-1.webp", "images/products/bracelet-enamel-2.webp", "images/products/bracelet-enamel-3.webp"]
  },
  {
    id: "raw-stone-bracelet",
    category: "bracelet",
    name: "天然原石手串",
    number: "DLYS-SC-005",
    material: "天然朱砂原石珠、弹力绳",
    size: "天然随形，多珠径可选",
    tagline: "原生矿纹，一串一天成",
    description: "精选保留天然矿物纹理的朱砂原石珠，经打磨、抛光与手工串制，呈现每串各不相同的色泽肌理。",
    meaning: "取天然本真与圆珠和合之意，寄托坚定、圆满与守正的美好愿景。",
    images: ["images/products/bracelet-raw-stone-1.webp", "images/products/bracelet-raw-stone-2.webp", "images/products/bracelet-raw-stone-3.webp", "images/products/bracelet-raw-stone-4.webp", "images/products/bracelet-raw-stone-5.webp"]
  },
  {
    id: "crystal-pingan-pendant",
    category: "pendant",
    name: "晶体砂平安扣",
    number: "DLYS-DZ-006",
    material: "天然晶体砂、手工编绳",
    size: "多规格与绳色可选",
    tagline: "晶体可见，圆满常安",
    description: "以晶体砂制成经典平安扣，细腻抛光保留矿物晶体层次，适合日常佩戴与礼赠。",
    meaning: "外圆内圆象征通达圆满，承载平安顺遂的传统祝愿。",
    images: ["images/products/pendant-crystal-pingan-1.webp", "images/products/pendant-crystal-pingan-2.webp", "images/products/pendant-crystal-pingan-3.webp"]
  },
  {
    id: "enamel-gourd-sweater-chain",
    category: "pendant",
    subcategory: "毛衣链",
    name: "珐琅彩葫芦毛衣链",
    number: "DLYS-DZ-007",
    material: "朱砂、珐琅彩葫芦饰件、长链",
    size: "长款毛衣链，具体以实物为准",
    tagline: "葫芦纳福，衣间添彩",
    description: "以朱砂长链连接珐琅彩葫芦主坠，比例修长，适合搭配新中式服饰、旗袍与秋冬针织。",
    meaning: "葫芦谐音福禄，寄托福禄双全、和美相伴。",
    images: ["images/products/pendant-gourd-chain-1.webp", "images/products/pendant-gourd-chain-2.webp", "images/products/pendant-gourd-chain-3.webp"]
  },
  {
    id: "fortune-flower-earrings",
    category: "pendant",
    subcategory: "耳坠",
    name: "鸿运花开耳坠",
    number: "DLYS-DZ-008",
    material: "朱砂圆珠、珐琅彩花饰、耳饰配件",
    size: "成对耳坠，尺寸以实物为准",
    tagline: "花开见喜，耳畔生辉",
    description: "以蓝金珐琅花饰衬托朱砂圆珠，层次轻盈，适合节庆礼服与日常新中式穿搭。",
    meaning: "花开象征喜悦与新生，朱红寄托鸿运相随。",
    images: ["images/products/pendant-flower-earrings-1.webp"]
  },
  {
    id: "peony-flower-pendant",
    category: "pendant",
    name: "牡丹花吊坠",
    number: "DLYS-DZ-009",
    material: "朱砂、珐琅彩牡丹饰件、手工流苏",
    size: "长款吊坠，尺寸以实物为准",
    tagline: "牡丹呈瑞，福伴心安",
    description: "朱砂主坠配以立体牡丹与深色流苏，将传统花卉意象转化为适合当代服饰的长款吊坠。",
    meaning: "牡丹寓意花开富贵、喜乐丰盈。",
    images: ["images/products/pendant-peony-1.webp"]
  },
  {
    id: "fulu-108-pendant",
    category: "pendant",
    name: "108红晶砂福禄珠吊坠",
    number: "DLYS-DZ-010",
    material: "红晶砂珠、福禄主题配珠、手工编绳",
    size: "6mm、8mm 等珠径可选",
    tagline: "一百零八珠，福禄相随",
    description: "以 108 颗红晶砂珠串联福禄主题配珠，可作长链佩戴，也可多圈绕腕，适配多种使用方式。",
    meaning: "长串相连象征圆满延续，福禄主题寄托丰足安泰。",
    images: ["images/products/pendant-fulu108-1.webp", "images/products/pendant-fulu108-2.webp", "images/products/pendant-fulu108-3.webp"]
  },
  {
    id: "pingan-108-pendant",
    category: "pendant",
    name: "108平安扣吊坠",
    number: "DLYS-DZ-011",
    material: "红晶砂珠、平安扣主坠、手工编绳",
    size: "长款珠链，规格以实物为准",
    tagline: "长珠成链，平安相扣",
    description: "以 108 珠长链搭配圆润平安扣主坠，朱红层次统一，兼具佩戴感与东方仪式感。",
    meaning: "珠珠相连、环环相扣，寄托长久平安与圆满相伴。",
    images: ["images/products/pendant-pingan108-1.webp", "images/products/pendant-pingan108-2.webp"]
  },
  {
    id: "gourd-car-pendant",
    category: "pendant",
    subcategory: "车挂",
    name: "葫芦车挂",
    number: "DLYS-DZ-012",
    material: "红晶砂珠、葫芦主题饰件、流苏",
    size: "车内悬挂尺寸",
    tagline: "福禄随行，一路从容",
    description: "朱砂珠环绕葫芦主题主坠，配以清雅流苏，适合车内悬挂与空间点缀。",
    meaning: "葫芦寓意福禄，承载一路顺遂、出入平安的祝愿。",
    images: ["images/products/pendant-gourd-car-1.webp", "images/products/pendant-gourd-car-2.webp"]
  },
  {
    id: "pingan-car-pendant",
    category: "pendant",
    subcategory: "车挂",
    name: "平安扣车挂",
    number: "DLYS-DZ-013",
    material: "红晶砂平安扣、手工珠链、流苏",
    size: "车内悬挂尺寸",
    tagline: "一扣平安，常伴旅途",
    description: "以朱砂平安扣为视觉中心，连接圆珠与流苏，整体简洁稳重。",
    meaning: "平安扣寄托出入平安、旅途顺遂。",
    images: ["images/products/pendant-pingan-car-1.webp", "images/products/pendant-pingan-car-2.webp"]
  },
  {
    id: "yuanbao-car-pendant",
    category: "pendant",
    subcategory: "车挂",
    name: "元宝车挂",
    number: "DLYS-DZ-014",
    material: "红晶砂珠、元宝主题饰件、流苏",
    size: "车内悬挂尺寸",
    tagline: "元宝纳吉，鸿运随行",
    description: "以立体元宝为主坠，朱砂珠环绕成链，色彩明快而富有传统节庆意趣。",
    meaning: "元宝象征丰足与纳吉，寄托财禄丰盈。",
    images: ["images/products/pendant-yuanbao-car-1.webp", "images/products/pendant-yuanbao-car-2.webp"]
  },
  {
    id: "yuanbao-tassel-car-pendant",
    category: "pendant",
    subcategory: "车挂",
    name: "元宝流苏车挂",
    number: "DLYS-DZ-015",
    material: "红晶砂珠、元宝饰件、手工长流苏",
    size: "长流苏车挂，尺寸以实物为准",
    tagline: "流苏摇曳，财禄相随",
    description: "在元宝主题车挂基础上加入长流苏结构，行车光影中更具层次与动感。",
    meaning: "元宝纳福，流苏寓意福泽绵延。",
    images: ["images/products/pendant-yuanbao-tassel-1.webp", "images/products/pendant-yuanbao-tassel-2.webp"]
  },
  {
    id: "wedding-honor-car-pendant",
    category: "pendant",
    subcategory: "车挂",
    name: "凤冠霞帔·状元及第车挂",
    number: "DLYS-DZ-016",
    material: "朱砂主题珠饰、手工编结、流苏",
    size: "凤冠霞帔与状元及第主题可选",
    tagline: "礼冠呈瑞，锦绣前程",
    description: "以凤冠霞帔与状元及第为双主题，结合朱砂珠饰、传统编结与红色流苏，适合婚礼、升学与纪念礼赠。",
    meaning: "凤冠寓意和美嘉礼，状元主题寄托前程锦绣、金榜题名。",
    images: ["images/products/pendant-wedding-car-1.webp", "images/products/pendant-wedding-car-2.webp", "images/products/pendant-wedding-car-3.webp"]
  },
  {
    id: "eight-guardians-pendant",
    category: "pendant",
    name: "八大守护神吊坠",
    number: "DLYS-DZ-017",
    material: "朱砂雕刻主坠、手工编绳",
    size: "成人款、儿童款及多生肖主题可选",
    tagline: "八方守护，随身安然",
    description: "以八大守护神文化题材雕刻朱砂主坠，提供成人与儿童规格及多种绳色选择。",
    meaning: "传统守护题材承载护佑平安、坚定向善的文化寄托。",
    images: ["images/products/pendant-guardians-1.webp", "images/products/pendant-guardians-2.webp", "images/products/pendant-guardians-3.webp"]
  },
  {
    id: "enamel-wushipai-pendant",
    category: "pendant",
    name: "珐琅彩非遗赤金流云无事牌",
    number: "DLYS-DZ-018",
    material: "朱砂无事牌、珐琅彩工艺、编绳",
    size: "随身吊坠尺寸",
    tagline: "赤金流云，无事常安",
    description: "以素面无事牌为主体，融入赤金流云纹与珐琅彩细节，造型利落而富有层次。",
    meaning: "无事牌寄托平安无虞，流云象征自在从容。",
    images: ["images/products/pendant-enamel-wushipai-1.webp"]
  },
  {
    id: "enamel-liangyi-pingan-pendant",
    category: "pendant",
    name: "珐琅彩非遗两仪平安扣",
    number: "DLYS-DZ-019",
    material: "朱砂平安扣、珐琅彩工艺、编绳",
    size: "随身吊坠尺寸",
    tagline: "两仪相合，平安相依",
    description: "将两仪构图、朱砂平安扣与珐琅彩纹样结合，形成刚柔相济的东方佩饰。",
    meaning: "两仪寓意和合有序，平安扣寄托圆满顺遂。",
    images: ["images/products/pendant-enamel-liangyi-1.webp"]
  },
  {
    id: "enamel-weiyang-earrings",
    category: "accessory",
    name: "珐琅彩赤宝未央耳坠",
    number: "DLYS-PS-004",
    material: "朱砂、珐琅彩工艺、耳饰配件",
    size: "成对耳坠，尺寸以实物为准",
    tagline: "赤宝未央，耳畔华彩",
    description: "以赤金流云纹与朱砂主坠相衬，色泽沉稳，适合新中式礼服与日常雅致搭配。",
    meaning: "未央寓意美好绵延，朱红寄托喜乐常在。",
    images: ["images/products/accessory-weiyang-earrings-1.webp"]
  },
  {
    id: "red-crystal-earrings",
    category: "accessory",
    name: "红晶砂耳坠",
    number: "DLYS-PS-005",
    material: "红晶砂珠、耳饰金属配件",
    size: "多款式可选",
    tagline: "红晶点睛，轻盈相伴",
    description: "以通透红晶砂珠形成耳畔亮点，造型轻巧，适合通勤与节庆穿搭。",
    meaning: "朱红点睛，寓意见喜添彩。",
    images: ["images/products/accessory-red-crystal-earrings-1.webp"]
  },
  {
    id: "enamel-fulu-earrings",
    category: "accessory",
    name: "珐琅彩赤宝福禄耳坠",
    number: "DLYS-PS-006",
    material: "朱砂、珐琅彩花饰、耳饰配件",
    size: "成对耳坠，多造型可选",
    tagline: "福禄成双，花彩相映",
    description: "朱砂圆珠与珐琅彩花饰上下相连，以精巧比例呈现福禄主题。",
    meaning: "成双耳坠寓意和合，福禄主题寄托丰足吉庆。",
    images: ["images/products/accessory-fulu-earrings-1.webp", "images/products/accessory-fulu-earrings-2.webp", "images/products/accessory-fulu-earrings-3.webp"]
  },
  {
    id: "cinnabar-thangka-painting",
    category: "creative",
    name: "唐卡朱砂画",
    number: "DLYS-WC-003",
    material: "朱砂矿物颜料、唐卡工艺画面、装裱画框",
    size: "多主题与装裱规格可选",
    tagline: "矿物入画，庄严华彩",
    description: "以朱砂矿物红呈现唐卡题材，并通过完整画框与展陈场景展示其细密层次。",
    meaning: "唐卡承载庄严、专注与祝愿，是传统绘画与矿物色彩结合的代表。",
    images: ["images/products/painting-tangka-1.webp", "images/products/painting-tangka-2.webp"]
  },
  {
    id: "happy-family-painting",
    category: "creative",
    name: "幸福人家朱砂画",
    number: "DLYS-WC-004",
    material: "朱砂矿物颜料、装裱画框",
    size: "多规格可选",
    tagline: "山河暖红，幸福人家",
    description: "以朱砂红描绘山水与家园意象，画面层次温暖，适合客厅、会客区与文化礼赠。",
    meaning: "山水家园寄托家和业兴、幸福安泰。",
    images: ["images/products/painting-happy-home.webp"]
  },
  {
    id: "zhongkui-cinnabar-painting",
    category: "creative",
    name: "钟馗朱砂画",
    number: "DLYS-WC-005",
    material: "朱砂矿物颜料、装裱画框",
    size: "多规格可选",
    tagline: "丹青写意，正气入画",
    description: "以朱砂矿物色呈现钟馗文化题材，人物形象鲜明，适合文化空间与主题收藏。",
    meaning: "钟馗题材承载守正护佑、刚健无畏的传统文化意象。",
    images: ["images/products/painting-zhongkui.webp"]
  }
);

/* 非遗工艺按原资料的九类目录呈现，卡片同时显示子分类。 */
window.PRODUCTS.push(
  {
    id: "surname-qi-totem",
    category: "heritage",
    subcategory: "百家姓图腾类",
    name: "百家姓齐字图腾",
    number: "DLYS-FY-002",
    material: "朱砂工艺画面、木质装裱框",
    size: "竖式装裱，支持姓氏主题定制",
    tagline: "一姓一印，家脉相承",
    description: "以篆意图腾呈现齐姓文化符号，朱砂红与金色底面相映，适合家族纪念与文化礼赠。",
    meaning: "姓氏图腾寄托慎终追远、家风绵延。",
    images: ["images/products/heritage-surname-qi.webp"]
  },
  {
    id: "surname-yan-totem",
    category: "heritage",
    subcategory: "百家姓图腾类",
    name: "百家姓闫字图腾",
    number: "DLYS-FY-003",
    material: "朱砂工艺画面、木质装裱框",
    size: "竖式装裱，支持姓氏主题定制",
    tagline: "图腾成印，家风有承",
    description: "以篆意图腾呈现闫姓文化符号，完整保留资料图中的姓氏标识与装裱样式。",
    meaning: "一姓一脉，寄托家风长存、根脉相承。",
    images: ["images/products/heritage-surname-yan.webp"]
  },
  {
    id: "dragon-phoenix-silk-painting",
    category: "heritage",
    subcategory: "帛画类",
    name: "龙凤呈祥朱砂帛画",
    number: "DLYS-FY-004",
    material: "朱砂矿物颜料、手绘帛面、装裱框",
    size: "横式帛画，尺寸以实物为准",
    tagline: "帛上丹青，龙凤呈瑞",
    description: "在帛面上手绘龙凤呈祥纹样，以朱砂矿物红展现古朴层次与礼仪之美。",
    meaning: "龙凤和鸣寓意和合美满、吉庆相承。",
    images: ["images/products/heritage-silk-dragon-1.webp", "images/products/heritage-silk-dragon-2.webp"]
  },
  {
    id: "diamond-fu-hanging",
    category: "heritage",
    subcategory: "挂画类",
    name: "菱形福字朱砂挂画",
    number: "DLYS-FY-005",
    material: "朱砂工艺画面、菱形装裱框",
    size: "菱形挂画，尺寸以实物为准",
    tagline: "菱形纳福，入户见喜",
    description: "以菱形构图承载朱砂福字，适合玄关、茶室与节庆空间布置。",
    meaning: "福字居中，寄托福到家门、和乐安康。",
    images: ["images/products/heritage-hanging-diamond-fu.webp"]
  },
  {
    id: "dragon-phoenix-fu-hanging",
    category: "heritage",
    subcategory: "挂画类",
    name: "龙凤呈祥福字挂画",
    number: "DLYS-FY-006",
    material: "朱砂工艺画面、圆形装裱框",
    size: "圆形挂画，尺寸以实物为准",
    tagline: "龙凤拱福，和合圆满",
    description: "圆形福字画面融入龙凤纹样，朱砂红与金色细节相衬，庄重而喜庆。",
    meaning: "龙凤呈祥、福字居中，寓意家和福满。",
    images: ["images/products/heritage-hanging-dragon-fu.webp"]
  },
  {
    id: "wealth-scroll",
    category: "heritage",
    subcategory: "卷轴类",
    name: "财通四海朱砂卷轴",
    number: "DLYS-FY-007",
    material: "朱砂书画、织锦卷轴",
    size: "竖式卷轴，尺寸以实物为准",
    tagline: "朱卷展意，财通四海",
    description: "以传统卷轴形式装裱朱砂主题书画，收展有序，适合会客区与商务礼赠。",
    meaning: "财通四海寄托事业通达、丰足兴盛。",
    images: ["images/products/heritage-scroll-wealth.webp"]
  },
  {
    id: "fortune-scroll",
    category: "heritage",
    subcategory: "卷轴类",
    name: "福满天下朱砂卷轴",
    number: "DLYS-FY-008",
    material: "朱砂书画、织锦卷轴",
    size: "竖式卷轴，尺寸以实物为准",
    tagline: "一卷福意，满室生辉",
    description: "朱砂福字居于织锦卷轴中央，保留传统装裱比例与东方留白。",
    meaning: "福满天下寓意福泽广布、安康常在。",
    images: ["images/products/heritage-scroll-fortune.webp"]
  },
  {
    id: "collector-cinnabar-painting",
    category: "heritage",
    subcategory: "收藏画合成图",
    name: "收藏品朱砂画",
    number: "DLYS-FY-009",
    material: "朱砂矿物颜料、主题画面、装裱框",
    size: "多题材与规格可选",
    tagline: "名作入砂，雅藏成集",
    description: "集合人物、花鸟与吉祥题材的朱砂画作品，突出矿物色泽与收藏级装裱表现。",
    meaning: "以画载道，以藏传文，寄托文化珍藏与审美传承。",
    images: ["images/products/heritage-collector-painting.webp"]
  },
  {
    id: "heritage-thangka",
    category: "heritage",
    subcategory: "唐卡",
    name: "朱砂唐卡",
    number: "DLYS-FY-010",
    material: "朱砂矿物颜料、唐卡工艺画面",
    size: "多主题与规格可选",
    tagline: "丹砂入彩，细绘庄严",
    description: "以朱砂矿物色融入唐卡绘制与装裱，画面细密，兼具传统仪式感与艺术陈设价值。",
    meaning: "唐卡题材承载专注、庄严与美好祝愿。",
    images: ["images/products/heritage-thangka-1.webp", "images/products/heritage-thangka-2.webp"]
  },
  {
    id: "cinnabar-ceramic-qilin",
    category: "heritage",
    subcategory: "陶艺类",
    name: "麒麟朱砂陶摆件",
    number: "DLYS-FY-011",
    material: "陶土、朱砂工艺层、手工描金",
    size: "成对麒麟摆件，尺寸以实物为准",
    tagline: "麒麟呈瑞，朱陶生辉",
    description: "以麒麟瑞兽为造型，将陶艺塑形、朱砂呈色与描金工艺结合，适合案头与玄关陈设。",
    meaning: "麒麟象征仁瑞与吉庆，寄托家宅安宁、祥瑞相伴。",
    images: ["images/products/heritage-ceramic-qilin-1.webp", "images/products/heritage-ceramic-qilin-2.webp"]
  },
  {
    id: "cinnabar-ceramic-zodiac",
    category: "heritage",
    subcategory: "陶艺类",
    name: "十二生肖朱砂陶摆件",
    number: "DLYS-FY-012",
    material: "陶土、朱砂工艺层、描金",
    size: "十二生肖主题可选",
    tagline: "生肖成器，岁岁有瑞",
    description: "将生肖形象凝练为圆形朱砂陶面，手工呈色与描金细节各具差异。",
    meaning: "生肖连接岁时文化，寄托本命守护与岁岁吉祥。",
    images: ["images/products/heritage-ceramic-zodiac.webp"]
  },
  {
    id: "cinnabar-ceramic-zhuque",
    category: "heritage",
    subcategory: "陶艺类",
    name: "朱雀朱砂陶摆件",
    number: "DLYS-FY-013",
    material: "陶土、朱砂工艺层、手工描金",
    size: "圆形桌面摆件",
    tagline: "朱雀衔光，赤色呈祥",
    description: "以朱雀纹样为主体，朱砂红与金色线条相映，造型简洁而富有传统图腾气息。",
    meaning: "朱雀象征光明与生机，寄托鸿运启新。",
    images: ["images/products/heritage-ceramic-zhuque.webp"]
  },
  {
    id: "cinnabar-ceramic-fulu",
    category: "heritage",
    subcategory: "陶艺类",
    name: "朱砂福禄桌摆",
    number: "DLYS-FY-014",
    material: "朱砂陶、手工成型",
    size: "葫芦形桌面摆件",
    tagline: "葫芦成器，福禄盈堂",
    description: "以葫芦形制塑造朱砂陶桌摆，器形圆润，适合书房、茶席与玄关陈设。",
    meaning: "葫芦谐音福禄，寓意丰足安泰。",
    images: ["images/products/heritage-ceramic-fulu.webp"]
  },
  {
    id: "cinnabar-ceramic-fushi",
    category: "heritage",
    subcategory: "陶艺类",
    name: "朱砂福石摆件",
    number: "DLYS-FY-015",
    material: "朱砂陶、主题底座",
    size: "桌面陈设尺寸",
    tagline: "石承福意，稳重安然",
    description: "以天然石形为灵感塑造朱砂陶福石，并配以主题底座，保留质朴手作气息。",
    meaning: "福石寓意根基稳固、福气相随。",
    images: ["images/products/heritage-ceramic-fushi.webp"]
  },
  {
    id: "phoenix-cinnabar-incense-burner",
    category: "heritage",
    subcategory: "陶艺类",
    name: "朱砂陶凤香炉",
    number: "DLYS-FY-016",
    material: "陶土、朱砂工艺层、手工雕塑",
    size: "桌面香炉，手工作品略有差异",
    tagline: "凤纹入炉，香与瑞合",
    description: "以凤纹与朱砂陶结合，器身保留塑形与烧制肌理，可用于香事陈设。",
    meaning: "凤凰寓意和美祥瑞，香事承载清雅静心。",
    images: ["images/products/heritage-phoenix-incense-1.webp", "images/products/heritage-phoenix-incense-2.webp"]
  },
  {
    id: "dragon-cinnabar-incense-burner",
    category: "heritage",
    subcategory: "陶艺类",
    name: "朱砂陶龙香炉",
    number: "DLYS-FY-017",
    material: "陶土、朱砂工艺层、手工雕塑",
    size: "桌面香炉，手工作品略有差异",
    tagline: "龙纹盘器，一炉清雅",
    description: "将龙纹造型融入朱砂陶香炉，外壁保留鳞纹与手作色层，适合茶席与香事空间。",
    meaning: "龙纹象征进取与祥瑞，香炉寄托清和安定。",
    images: ["images/products/heritage-dragon-incense.webp"]
  },
  {
    id: "sailing-cinnabar-fan",
    category: "heritage",
    subcategory: "团扇类",
    name: "一帆风顺朱砂团扇",
    number: "DLYS-FY-018",
    material: "朱砂工艺扇面、扇骨、流苏",
    size: "圆形团扇",
    tagline: "一扇风雅，一帆顺遂",
    description: "圆形扇面绘制帆船主题，以朱砂红点染东方祝愿，兼具陈设与文化礼赠属性。",
    meaning: "一帆风顺寓意行稳致远、诸事顺遂。",
    images: ["images/products/heritage-fan-sailing.webp"]
  },
  {
    id: "fu-cinnabar-fan",
    category: "heritage",
    subcategory: "团扇类",
    name: "朱砂福字团扇",
    number: "DLYS-FY-019",
    material: "朱砂工艺扇面、扇骨、流苏",
    size: "圆形团扇",
    tagline: "扇纳清风，福意常在",
    description: "以朱砂福字为扇面中心，结合传统团扇轮廓，适合节庆陈设与伴手礼。",
    meaning: "福字团扇寓意迎福纳祥、和乐安康。",
    images: ["images/products/heritage-fan-fu.webp"]
  },
  {
    id: "cinnabar-jade-tea-set",
    category: "heritage",
    subcategory: "朱砂玉茶具类",
    name: "朱砂玉茶具",
    number: "DLYS-FY-020",
    material: "朱砂玉工艺材质、茶具配件",
    size: "茶壶及配套器具，规格以实物为准",
    tagline: "朱玉成器，茶席生辉",
    description: "以朱砂玉质感呈现圆润茶器造型，色泽沉稳，适合茶席陈设、文化交流与礼赠。",
    meaning: "茶和万物，圆器纳福，寄托宾主和悦、雅集长欢。",
    images: ["images/products/heritage-tea-set-1.webp", "images/products/heritage-tea-set-2.webp"]
  }
);
